#!/usr/bin/env python3
"""Generate 2-dim ASTRA-sim analytical network YAMLs for Loom experiments.

dim0 = rack scale-up fabric, traversed through the (Loom) ToR switch
dim1 = inter-ToR Ethernet

The Loom switch is modeled as constants folded into the existing per-dimension
`latency` and `bandwidth` fields (the HGX-H100-validated.yml technique):
  - dim latency  += pipe_ns          (switch pipeline: validate/match/bounds/translate)
  - dim1 bandwidth *= goodput        (encap header + coalescing efficiency)

Modes:
  loom      pipe adder on both dims (every hop crosses the ToR datapath);
            Loom goodput on dim1
  baseline  no Loom pipe; dim1 pays NIC endpoint elsewhere (system JSON) and
            plain RoCE goodput
  ideal     no adders, goodput 1.0 (upper bound B3)

Example:
  ./gen_network_config.py --mode loom --racks 8 --xpus-per-rack 16 \
      --pipe-ns 500 --loom-goodput 0.94 -o network/loom_8racks_16xpus.yml
"""

import argparse
import sys

MODES = ("loom", "baseline", "ideal")


def build_yaml(args) -> str:
    if args.mode == "loom":
        # in-rack: the Loom ToR IS the rack switch (whose forwarding is
        # already inside fabric_latency); Loom adds only the table lookups
        lat0 = args.fabric_latency + args.pipe_local_ns
        # source ToR: full remote pipeline (lookup/validate + encap) + RoCE
        # TX streaming. Destination ToR: RoCE RX streaming + decap + the SAME
        # check/translate/forward the local route does (both routes converge
        # on the transaction generator, design 6.1) -> t_pipe_local, not a
        # second t_pipe. T3 measures the end-to-end sum.
        # plus the physical edge legs (XPU->source ToR, dest ToR->XPU):
        # one full fabric traversal, same elements as an in-rack trip. The
        # baseline's rdma_init anchor is end-to-end and already includes
        # its PCIe legs, so only Loom needs them added explicitly.
        lat1 = (args.fabric_latency
                + args.net_latency
                + (args.pipe_ns + args.roce_stack_ns)
                + (args.roce_stack_ns + args.pipe_local_ns))
        # equal-wires provisioning: ToR uplink aggregate = M NICs' aggregate,
        # divided by the explicit oversubscription factor
        bw1 = args.net_bw * args.loom_goodput / args.uplink_oversub
    elif args.mode == "baseline":
        lat0 = args.fabric_latency
        # RDMA initiation is paid per scale-out op only (a dim1 crossing);
        # in-rack peer access is a plain store, same as Loom's
        lat1 = args.net_latency + args.rdma_init_ns
        bw1 = args.net_bw * args.roce_goodput
    else:  # ideal
        lat0 = args.fabric_latency
        lat1 = args.net_latency
        bw1 = args.net_bw

    cmd = " ".join(sys.argv)
    return (
        f"# generated by: {cmd}\n"
        f"# mode={args.mode}: dim0 = rack fabric (through ToR), dim1 = inter-ToR Ethernet\n"
        f"topology: [ Switch, {args.dim1_topology} ]\n"
        f"npus_count: [ {args.xpus_per_rack}, {args.racks} ]\n"
        f"bandwidth: [ {args.fabric_bw:.2f}, {bw1:.2f} ]  # GB/s\n"
        f"latency: [ {lat0:.2f}, {lat1:.2f} ]  # ns\n"
    )


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--mode", choices=MODES, required=True)
    p.add_argument("--racks", type=int, required=True)
    p.add_argument("--xpus-per-rack", type=int, required=True)
    # physical substrate (identical across modes: fairness rule F1)
    p.add_argument("--fabric-bw", type=float, default=64.0,
                   help="rack fabric GB/s per XPU link (default: PCIe5 x16 effective)")
    p.add_argument("--fabric-latency", type=float, default=500.0,
                   help="rack fabric wire+hop ns (default 500)")
    p.add_argument("--net-bw", type=float, default=50.0,
                   help="inter-ToR GB/s per uplink (default: 400GbE)")
    p.add_argument("--net-latency", type=float, default=600.0,
                   help="inter-ToR wire+switch one-way ns (cut-through ToR "
                        "class, 300-800ns datasheets + propagation)")
    # Loom / baseline constants (placeholders; see README table)
    p.add_argument("--pipe-ns", type=float, default=200.0,
                   help="Loom SOURCE-side remote pipeline: lookup/match/encap "
                        "only (transport + destination work priced "
                        "separately). ASIC-class pipelined lookups ~100-300ns "
                        "-> placeholder 200, swept; testbed T3 (FPGA will "
                        "read higher; sweep carries the FPGA/ASIC argument)")
    p.add_argument("--pipe-local-ns", type=float, default=50.0,
                   help="Loom LOCAL-route adder over stock switch forwarding "
                        "(binding lookup + bounds; pipelined table lookups, "
                        "placeholder 50; testbed T3 measures vs raw Coyote)")
    p.add_argument("--loom-goodput", type=float, default=0.947,
                   help="Loom encap goodput factor at the run's message mix")
    p.add_argument("--roce-goodput", type=float, default=0.95,
                   help="baseline RoCE goodput factor")
    p.add_argument("--roce-stack-ns", type=float, default=150.0,
                   help="transport STREAMING share per ToR traversal, "
                        "inside the switch pipeline: packet build/ICRC/CC "
                        "state only. Loom initiates no work requests on "
                        "the data path (connections pre-established in the "
                        "control path; no doorbell/WQE/payload DMA - those "
                        "are precisely the baseline rdma-init components). "
                        "Coyote RoCE floor measures this; set 0 if "
                        "--pipe-ns is measured inclusive")
    p.add_argument("--rdma-init-ns", type=float, default=2400.0,
                   help="baseline per-op RDMA initiation cost after the wire, "
                        "folded into dim1 (B1 GPU-initiated 2400 -> ~3us "
                        "end-to-end, IBGDA/NVSHMEM-class; B2 CPU proxy 2800 "
                        "-> ib_write_lat + proxy handoff; swept)")
    p.add_argument("--dim1-topology", choices=("Switch", "Ring", "FullyConnected"),
                   default="Switch", help="inter-ToR topology (default Switch)")
    p.add_argument("--uplink-oversub", type=float, default=1.0,
                   help="Loom ToR uplink oversubscription vs per-XPU NICs "
                        "(1.0 = equal wires; sweep per eval plan S-6)")
    p.add_argument("-o", "--output", default="-")
    args = p.parse_args()

    text = build_yaml(args)
    if args.output == "-":
        sys.stdout.write(text)
    else:
        with open(args.output, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
