#!/usr/bin/env python3
"""Generate 2-dim ASTRA-sim analytical network YAMLs for Loom experiments.

dim0 = rack scale-up fabric, traversed through the (Loom) ToR switch
dim1 = inter-ToR Ethernet

The Loom switch is modeled as constants folded into the existing per-dimension
`latency` and `bandwidth` fields (the HGX-H100-validated.yml technique):
  - dim latency  += pipe_ns          (switch pipeline: validate/match/bounds/translate)
  - dim1 bandwidth *= goodput        (encap header + coalescing efficiency)

Modes:
  loom      pipe adder on both dims (every hop crosses the ToR datapath);
            Loom goodput on dim1
  baseline  no Loom pipe; dim1 pays NIC endpoint elsewhere (system JSON) and
            plain RoCE goodput
  ideal     no adders, goodput 1.0 (upper bound B3)

Example:
  ./gen_network_config.py --mode loom --racks 8 --xpus-per-rack 16 \
      --pipe-ns 500 --loom-goodput 0.94 -o network/loom_8racks_16xpus.yml
"""

import argparse
import sys

MODES = ("loom", "baseline", "ideal")


def build_yaml(args) -> str:
    if args.mode == "loom":
        lat0 = args.fabric_latency + args.pipe_ns
        # source + destination ToR pipelines + the RoCE stack the Loom
        # switch itself uses (baselines' published numbers include their NIC)
        lat1 = args.net_latency + args.roce_stack_ns + 2 * args.pipe_ns
        # equal-wires provisioning: ToR uplink aggregate = M NICs' aggregate,
        # divided by the explicit oversubscription factor
        bw1 = args.net_bw * args.loom_goodput / args.uplink_oversub
    elif args.mode == "baseline":
        lat0 = args.fabric_latency
        # RDMA initiation is paid per scale-out op only (a dim1 crossing);
        # in-rack peer access is a plain store, same as Loom's
        lat1 = args.net_latency + args.rdma_init_ns
        bw1 = args.net_bw * args.roce_goodput
    else:  # ideal
        lat0 = args.fabric_latency
        lat1 = args.net_latency
        bw1 = args.net_bw

    cmd = " ".join(sys.argv)
    return (
        f"# generated by: {cmd}\n"
        f"# mode={args.mode}: dim0 = rack fabric (through ToR), dim1 = inter-ToR Ethernet\n"
        f"topology: [ Switch, {args.dim1_topology} ]\n"
        f"npus_count: [ {args.xpus_per_rack}, {args.racks} ]\n"
        f"bandwidth: [ {args.fabric_bw:.2f}, {bw1:.2f} ]  # GB/s\n"
        f"latency: [ {lat0:.2f}, {lat1:.2f} ]  # ns\n"
    )


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--mode", choices=MODES, required=True)
    p.add_argument("--racks", type=int, required=True)
    p.add_argument("--xpus-per-rack", type=int, required=True)
    # physical substrate (identical across modes: fairness rule F1)
    p.add_argument("--fabric-bw", type=float, default=64.0,
                   help="rack fabric GB/s per XPU link (default: PCIe5 x16 effective)")
    p.add_argument("--fabric-latency", type=float, default=500.0,
                   help="rack fabric wire+hop ns (default 500)")
    p.add_argument("--net-bw", type=float, default=50.0,
                   help="inter-ToR GB/s per uplink (default: 400GbE)")
    p.add_argument("--net-latency", type=float, default=600.0,
                   help="inter-ToR wire+switch one-way ns (cut-through ToR "
                        "class, 300-800ns datasheets + propagation)")
    # Loom / baseline constants (placeholders; see README table)
    p.add_argument("--pipe-ns", type=float, default=500.0,
                   help="Loom switch pipeline latency t_loom_pipe (placeholder 500)")
    p.add_argument("--loom-goodput", type=float, default=0.947,
                   help="Loom encap goodput factor at the run's message mix")
    p.add_argument("--roce-goodput", type=float, default=0.95,
                   help="baseline RoCE goodput factor")
    p.add_argument("--roce-stack-ns", type=float, default=700.0,
                   help="RoCE/NIC stack processing paid by the Loom switch "
                        "on the cross-rack route (NIC-class; testbed T3)")
    p.add_argument("--rdma-init-ns", type=float, default=2400.0,
                   help="baseline per-op RDMA initiation cost after the wire, "
                        "folded into dim1 (B1 GPU-initiated 2400 -> ~3us "
                        "end-to-end, IBGDA/NVSHMEM-class; B2 CPU proxy 2800 "
                        "-> ib_write_lat + proxy handoff; swept)")
    p.add_argument("--dim1-topology", choices=("Switch", "Ring", "FullyConnected"),
                   default="Switch", help="inter-ToR topology (default Switch)")
    p.add_argument("--uplink-oversub", type=float, default=1.0,
                   help="Loom ToR uplink oversubscription vs per-XPU NICs "
                        "(1.0 = equal wires; sweep per eval plan S-6)")
    p.add_argument("-o", "--output", default="-")
    args = p.parse_args()

    text = build_yaml(args)
    if args.output == "-":
        sys.stdout.write(text)
    else:
        with open(args.output, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
